# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b6f0cc59d28163a9af9eb6b2cb4e3b2ecfd7fa4a2de9c33d5e9b479691e0f714df81b24cc69226910662077e6f79db4a2d3411c1e7fc06352a888a46dbb4e6

test:
  secret_key_base: 27216f1075a9ab60cd99b860784cddbdacc6f4a9f8316d8dc482b8edb1481a38639b54a9eaa156b3c895917589a2de9ef046b0924da5a3e72a0de3e27aa9ffda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
